name: Lint and Test
on: [push, pull_request]
jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/prep
      env:
        VAULT_PASS: ${{ secrets.VAULT_PASS }}
    - name: hide credentials from the output
      run: |
        echo "::add-mask::$POSTGRES_USER"
        echo "::add-mask::$POSTGRES_PASSWORD"
        echo "::add-mask::$POSTGRES_DB"
    - name: build docker containers
      run: |
        docker-compose build
    - name: Lint web using flake8 in web docker container
      run: |
        docker-compose run web bash -c \
          "flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics \
           && flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics"
    - name: Basic smoke test
      run: |
        docker-compose up --build --detach
        sleep 10
        curl --fail localhost:8000
